### ISSUE TITLE
Throws an error if called from module without parent / which only called itself

### ISSUE THREAD

**Issue by dummdidumm** [sindresorhus/import-fresh#18]
I have the situation where after bundling with Rollup I get an error when trying to resolve a config file through [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) and traced the error back to this package.

In my situation, after bundling, the bundled file is the top level module and `import-fresh` and the packages it depends on are also in that same file. [The call to parent-module](https://github.com/sindresorhus/import-fresh/blob/master/index.js#L11) then returns undefined because the call stack only consists of the file itself. [The next call to resolve-from](https://github.com/sindresorhus/import-fresh/blob/master/index.js#L13) on the other hand expects the filePath to be a string and throws. I think falling back to the moduleId-path or `__filename` should be done instead.

I can reproduce this if I place the code of `import-fresh` in the same file and invoke it like this:

```js
const path = require('path');
const resolveFrom = require('resolve-from');
const parentModule = require('parent-module');

// code of import-fresh ...

function a() {
    b();
}
function b() {
    c();
}
// repeat until....
function h() {
   importFresh('./doesnt-matter');
}
a();
```

Reproduced on Windows 10 with node v14.5.0

I'm still not sure if I'm doing something wrong elsewhere because your package is used by so many other packages and noone has opened this issue yet.

**Comment by JulienKode** [comment]
We have the same issue in this GitHub Action: https://github.com/JulienKode/pull-request-name-linter-action/issues/61 

https://github.com/sindresorhus/import-fresh/pull/19 can fix the issue I think
