### ISSUE TITLE
Transparent module.parent

### ISSUE THREAD

**Issue by mightyiam** [sindresorhus/import-fresh#5]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/import-fresh/issues/5)

`module.parent` in module required by `requireUncached` will be the `[...]/require-uncached/index.js` module.

Can we please fix it to be the parent of that? Meaning, the `module.parent.parent`? I think it makes sense.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#13 Make parent transparent](https://issuehunt.io/r/sindresorhus/import-fresh/pull/13)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/import-fresh/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
👍 Pull request welcome :)

**Comment by mightyiam** [comment]
Does anyone have a pointer for me?

**Comment by sindresorhus** [comment]
I think you could use [`Module._load`](https://github.com/nodejs/node/blob/db18dd83567ff45b7d6236053053b3b90aaca357/lib/module.js#L413) (what `require()` uses) with a custom module entry to be able to set the parent. Another possible solution could be to modify `require.cache`.
