### ISSUE TITLE
Fails with "Path must be a string" on Node 8

### ISSUE THREAD

**Issue by marionebl** [sindresorhus/import-fresh#6]
In certain conditions `import-fresh` fails with the error message `Path must be a string. Received null` on Node 8.

```js
importFresh('global-dirs');
```

```
 Path must be a string. Received null
  module.exports.moduleId (~/node_modules/import-fresh/index.js:11:36)
  ...
```

Example build: [travis/commitlint#L1738](https://travis-ci.org/marionebl/commitlint/jobs/304224806#L1738)

Digging deeper reveals this is caused by `caller-path` returning a `Callsite` that returns null from its `getFileName` method: [caller-path/index.js#L4](https://github.com/sindresorhus/caller-path/blob/622c284b4aa5f8757283dbd494d0f39b5528f7d9/index.js#L4)

This in turn is caused by `caller-callsite` returning always the very first `Callsite` it finds by breaking out of the iteration here: [caller-callsite/index.js#L13](https://github.com/sindresorhus/caller-callsite/blob/1ce43fc89a890a702f5da866ed151b14e2ff54e5/index.js#L13)

Removing the `break` statement fixes the issue for me - I am not familiar with the APIs used here, so I am not very confident this is the appropriate fix though.

## Steps to reproduce

```sh
n 8.9.1
git clone https://github.com/marionebl/commitlint.git
cd commitlint 
git checkout import-fresh-null-repro
npx lerna bootstrap
cd `@commitlint/core
npx ava src/library/resolve-extends.test.js
```

**Comment by Aladdin-ADD** [comment]
same issue in eslint: https://github.com/eslint/eslint/pull/11066

**Comment by Aladdin-ADD** [comment]
friendly ping @sindresorhus

**Comment by Aladdin-ADD** [comment]
@sindresorhus seems the issue could be closed!

**Comment by sindresorhus** [comment]
Great!
