### ISSUE TITLE
renaming not documented

### ISSUE THREAD

**Issue by Aladdin-ADD** [sindresorhus/import-fresh#8]

**Comment by sindresorhus** [comment]
?

**Comment by Aladdin-ADD** [comment]
sorry for unclear. the package has been renamed from `require-uncached` to `import-fresh` in https://github.com/sindresorhus/import-fresh/commit/91d153983929b49e84192f5e8fefa783b3451729
but seems it was not documented.

**Comment by sindresorhus** [comment]
Seems I forgot to deprecate the old name on npm. Done now: https://www.npmjs.com/package/require-uncached
